// flower-svg.ts — SHAPE_PARAMS definitions and flowerSVG entry point.
// Extracted from game.js for reuse and type safety.

import { lighter, darker } from "./color-utils";
import { _svg } from "./svg-helpers";
import { FLOWER_RENDERERS } from "./renderers";
import type { FlowerDef, ShapeParams } from "./types";

// ── Shape parameters for all flower appearances ────────────────
// fn: renderer key | radial: n petals | cup: open 0=tight->1=wide
// spike: cols/rows | star: n wide petals | bell: bells count

export const SHAPE_PARAMS: Record<string, ShapeParams> = {
  // ── RADIAL ───────────────────────────────────────────────────
  sunflower: {
    fn: "radial",
    n: 8,
    rx: 5.5,
    ry: 11,
    cy: 33,
    cR: 10,
    cFill: "#795548",
    c2R: 8,
    c2Fill: "#4e342e",
    leaves: true,
  },
  daisy: {
    fn: "radial",
    n: 12,
    rx: 3.5,
    ry: 9,
    cy: 41,
    cR: 10,
    cFill: "#fdd835",
    c2R: 8,
    c2Fill: "#f9a825",
    leaves: true,
  },
  cosmos: {
    fn: "radial",
    n: 8,
    rx: 4,
    ry: 10,
    cy: 40,
    cR: 8,
    cFill: "#ce93d8",
    leaves: true,
  },
  zinnia: {
    fn: "radial",
    n: 10,
    rx: 3.5,
    ry: 9,
    cy: 40,
    cR: 8,
    cFill: "#fdd835",
    c2R: 6,
    c2Fill: "#f9a825",
    leaves: true,
  },
  aster: {
    fn: "radial",
    n: 14,
    rx: 3,
    ry: 8,
    cy: 40,
    cR: 8,
    cFill: "#fdd835",
    leaves: true,
  },
  gerbera: {
    fn: "radial",
    n: 16,
    rx: 3,
    ry: 8,
    cy: 40,
    cR: 7,
    cFill: "#1a1a1a",
    c2R: 5,
    c2Fill: "#263238",
    leaves: true,
  },
  marigold: {
    fn: "radial",
    n: 14,
    rx: 3,
    ry: 7,
    cy: 38,
    cR: 8,
    cFill: "#e65100",
    leaves: true,
  },
  calendula: {
    fn: "radial",
    n: 12,
    rx: 3,
    ry: 8,
    cy: 40,
    cR: 7,
    cFill: "#e65100",
    c2R: 5,
    c2Fill: "#bf360c",
    leaves: true,
  },
  blackeyedsusan: {
    fn: "radial",
    n: 12,
    rx: 3.5,
    ry: 9,
    cy: 40,
    cR: 7,
    cFill: "#1a1a1a",
    c2R: 5,
    c2Fill: "#37474f",
    leaves: true,
  },
  cornflower: {
    fn: "radial",
    n: 12,
    rx: 3,
    ry: 7,
    cy: 40,
    cR: 6,
    cFill: "#1e88e5",
    leaves: true,
  },
  allium: {
    fn: "radial",
    n: 16,
    rx: 2,
    ry: 5,
    cy: 36,
    cR: 5,
    cFill: "#6a1b9a",
    leaves: true,
  },
  forgetmenot: {
    fn: "radial",
    n: 5,
    rx: 4,
    ry: 7,
    cy: 40,
    cR: 5,
    cFill: "#fdd835",
    leaves: false,
  },
  cherry: {
    fn: "notched",
    n: 5,
    cy: 40,
    cR: 7,
    cFill: "#c62828",
  },
  violet: {
    fn: "asymmetric",
    cy: 38,
    cR: 5,
    cFill: "#fdd835",
  },
  anemone: {
    fn: "radial",
    n: 6,
    rx: 6.5,
    ry: 10,
    cy: 40,
    cR: 8,
    cFill: "#1a1a1a",
    c2R: 5,
    c2Fill: "#263238",
    leaves: true,
  },
  pansy: {
    fn: "radial",
    n: 5,
    rx: 9,
    ry: 9,
    cy: 38,
    cR: 6,
    cFill: "#f9a825",
    leaves: true,
  },
  jasmine: {
    fn: "radial",
    n: 5,
    rx: 3,
    ry: 9,
    cy: 40,
    cR: 4,
    cFill: "#f9a825",
    leaves: false,
  },
  geranium: {
    fn: "radial",
    n: 5,
    rx: 7,
    ry: 7,
    cy: 40,
    cR: 7,
    cFill: "#fdd835",
    leaves: true,
  },
  primrose: {
    fn: "radial",
    n: 5,
    rx: 5,
    ry: 10,
    cy: 38,
    cR: 6,
    cFill: "#fdd835",
    c2R: 4,
    c2Fill: "#f9a825",
    leaves: false,
  },
  phlox: {
    fn: "radial",
    n: 5,
    rx: 5.5,
    ry: 7,
    cy: 40,
    cR: 4,
    cFill: "#fdd835",
    leaves: false,
  },
  impatiens: {
    fn: "radial",
    n: 5,
    rx: 7,
    ry: 6,
    cy: 40,
    cR: 5,
    cFill: "#fdd835",
    leaves: false,
  },
  nasturtium: {
    fn: "radial",
    n: 5,
    rx: 8.5,
    ry: 8,
    cy: 39,
    cR: 4,
    cFill: "#f9a825",
    leaves: true,
  },
  sweetpea: {
    fn: "radial",
    n: 5,
    rx: 3.5,
    ry: 7,
    cy: 42,
    cR: 3,
    cFill: "#fce4ec",
    leaves: false,
  },
  wallflower: {
    fn: "radial",
    n: 4,
    rx: 5,
    ry: 8,
    cy: 40,
    cR: 5,
    cFill: "#795548",
    leaves: false,
  },
  clematis: {
    fn: "radial",
    n: 6,
    rx: 7.5,
    ry: 9,
    cy: 39,
    cR: 6,
    cFill: "#fdd835",
    c2R: 4,
    c2Fill: "#f9a825",
    leaves: false,
  },
  alstroemeria: {
    fn: "radial",
    n: 6,
    rx: 3.5,
    ry: 11,
    cy: 38,
    cR: 5,
    cFill: "#f9a825",
    leaves: true,
  },
  verbena: {
    fn: "radial",
    n: 5,
    rx: 3,
    ry: 5,
    cy: 42,
    cR: 3,
    cFill: "#fdd835",
    leaves: false,
  },
  gaillardia: {
    fn: "radial",
    n: 12,
    rx: 3.5,
    ry: 8,
    cy: 40,
    cR: 7,
    cFill: "#795548",
    c2R: 5,
    c2Fill: "#4e342e",
    leaves: true,
  },
  plumeria: {
    fn: "radial",
    n: 5,
    rx: 4,
    ry: 13,
    cy: 37,
    cR: 6,
    cFill: "#fdd835",
    leaves: false,
  },
  lotus: {
    fn: "radial",
    n: 8,
    rx: 5,
    ry: 10,
    cy: 38,
    cR: 7,
    cFill: "#fdd835",
    c2R: 5,
    c2Fill: "#f9a825",
    leaves: true,
  },
  lantana: {
    fn: "radial",
    n: 5,
    rx: 3.5,
    ry: 6,
    cy: 40,
    cR: 5,
    cFill: "#fdd835",
    leaves: false,
  },
  hellebore: {
    fn: "radial",
    n: 5,
    rx: 8,
    ry: 7,
    cy: 39,
    cR: 7,
    cFill: "#fdd835",
    leaves: true,
  },
  // ── CUP (open: 0=tight tulip -> 1=wide poppy) ─────────────────
  tulip: { fn: "cup", open: 0 },
  crocus: { fn: "cup", open: 0.3 },
  poppy: { fn: "cup", open: 1 },
  hibiscus: { fn: "cup", open: 0.9 },
  petunia: { fn: "cup", open: 0.85 },
  morningglory: { fn: "cup", open: 0.8 },
  azalea: { fn: "cup", open: 0.6 },
  cyclamen: { fn: "cup", open: 0.35 },
  // ── SPIKE (cols:1=single|2=paired; rows:blob count) ───────────
  lavender: { fn: "spike", cols: 2, rows: 8 },
  hyacinth: { fn: "spike", cols: 2, rows: 9 },
  foxglove: { fn: "spike", cols: 1, rows: 9 },
  gladiolus: { fn: "spike", cols: 1, rows: 4 },
  snapdragon: { fn: "spike", cols: 1, rows: 6 },
  salvia: { fn: "spike", cols: 2, rows: 10 },
  veronica: { fn: "spike", cols: 1, rows: 7 },
  buddleia: { fn: "spike", cols: 2, rows: 11 },
  stock: { fn: "spike", cols: 2, rows: 7 },
  statice: { fn: "spike", cols: 2, rows: 6 },
  freesia: { fn: "spike", cols: 1, rows: 5 },
  heather: { fn: "spike", cols: 2, rows: 5 },
  // ── STAR (wide flat petals: lily/iris/orchid type) ────────────
  lily: { fn: "star", n: 6, rx: 5, ry: 12, cy: 38, cR: 0, cFill: "" },
  iris: { fn: "standards", cy: 38, cR: 5, cFill: "#fdd835" },
  orchid: {
    fn: "labellum",
    cy: 36,
    cR: 5,
    cFill: "#f06292",
    lipColor: "#e91e63",
  },
  daffodil: {
    fn: "star",
    n: 6,
    rx: 5.5,
    ry: 12,
    cy: 38,
    cR: 11,
    cFill: "#f9a825",
  },
  magnolia: { fn: "star", n: 6, rx: 7, ry: 12, cy: 37, cR: 0, cFill: "" },
  saffron: { fn: "star", n: 6, rx: 4, ry: 10, cy: 40, cR: 5, cFill: "#f9a825" },
  amaryllis: {
    fn: "star",
    n: 6,
    rx: 6,
    ry: 11,
    cy: 37,
    cR: 6,
    cFill: "#fdd835",
  },
  // ── BELL (drooping pendant bells) ────────────────────────────
  bluebell: { fn: "bell", bells: 4, bw: 5, bh: 8 },
  lilyvalley: { fn: "bell", bells: 4, bw: 4, bh: 6 },
  fuchsia: { fn: "bell", bells: 2, bw: 6, bh: 9 },
  wisteria: { fn: "bell", bells: 4, bw: 5, bh: 7 },
  gloxinia: { fn: "bell", bells: 2, bw: 7, bh: 9 },
  bleedingheart: { fn: "bell", bells: 3, bw: 5, bh: 9 },
  bromeliad: { fn: "bell", bells: 2, bw: 7, bh: 8 },
  bougainvillea: { fn: "bell", bells: 4, bw: 6, bh: 7 },
  // ── ROSETTE (layered concentric petal circles) ─────────────────
  rose: { fn: "rosette", cy: 35, r0: 18, tight: 0.5 },
  peony: { fn: "rosette", cy: 33, r0: 19, tight: 0.45, yellowCenter: true },
  carnation: { fn: "rosette", cy: 36, r0: 14, tight: 0.59 },
  dahlia: { fn: "rosette", cy: 33, r0: 20, tight: 0.43 },
  chrysanthemum: { fn: "rosette", cy: 37, r0: 15, tight: 0.5 },
  ranunculus: { fn: "rosette", cy: 37, r0: 17, tight: 0.44 },
  begonia: { fn: "rosette", cy: 38, r0: 13, tight: 0.52 },
  hydrangea: { fn: "rosette", cy: 39, r0: 11, tight: 0.65 },
  gardenia: { fn: "rosette", cy: 36, r0: 18, tight: 0.42 },
  camellia: { fn: "rosette", cy: 36, r0: 15, tight: 0.54 },
};

// ── Flower data lookup type ────────────────────────────────────

/** Record of all flower definitions, keyed by flower ID. */
export type FlowerMap = Record<string, FlowerDef>;

// ── Main entry point ───────────────────────────────────────────

/**
 * Render a flower SVG string for the given flower key and growth stage.
 *
 * @param key   - Flower ID (key into the FLOWERS record)
 * @param stage - Growth stage: 0=seed, 1=sprout, 2=budding, 3=bloomed
 * @param flowers - The FLOWERS data record (passed in to avoid circular dependency)
 */
export function flowerSVG(key: string, stage: number, flowers: FlowerMap): string {
  const f = flowers[key];
  if (!f) return _svg(`<text x="30" y="52" text-anchor="middle" font-size="9" fill="#aaa">?</text>`);
  const p = f.petal,
    S = f.stem;
  const pl = lighter(p),
    pll = lighter(p, 85),
    pd = darker(p),
    SD = darker(S, 25);
  if (stage === 0)
    return `<svg viewBox="0 0 60 100" fill="none" xmlns="http://www.w3.org/2000/svg">
    <ellipse cx="30" cy="95" rx="14" ry="4" fill="#6d4c41" opacity=".3"/>
    <path d="M30 93 Q26 78 28 64 Q30 70 32 64 Q34 78 30 93" fill="${S}"/>
    <ellipse cx="30" cy="62" rx="5" ry="4" fill="${SD}" opacity=".9"/>
  </svg>`;
  const P = SHAPE_PARAMS[f.appearance] || SHAPE_PARAMS[f.kind];
  if (!P)
    return _svg(
      `<text x="30" y="52" text-anchor="middle" font-size="9" fill="#aaa">?</text>`,
    );
  return FLOWER_RENDERERS[P.fn](f, stage, P);
}
