import type { FlowerDef } from './types';

export const FLOWERS: Record<string, FlowerDef> = {
  // -- Common (59) ---------------------------------------------------------
  pinkTulip: {
    name: "Pink Tulip",
    kind: "tulip",
    appearance: "tulip",
    rarity: "common",
    w: 32,
    petal: "#f06292",
    stem: "#66bb6a",
    sell: 5,
  },
  redTulip: {
    name: "Red Tulip",
    kind: "tulip",
    appearance: "tulip",
    rarity: "common",
    w: 28,
    petal: "#e53935",
    stem: "#66bb6a",
    sell: 6,
  },
  yellowTulip: {
    name: "Yellow Tulip",
    kind: "tulip",
    appearance: "tulip",
    rarity: "common",
    w: 24,
    petal: "#fdd835",
    stem: "#66bb6a",
    sell: 6,
  },
  purpleViolet: {
    name: "Purple Violet",
    kind: "violet",
    appearance: "violet",
    rarity: "common",
    w: 20,
    petal: "#7e57c2",
    stem: "#66bb6a",
    sell: 5,
  },
  blueViolet: {
    name: "Blue Violet",
    kind: "violet",
    appearance: "violet",
    rarity: "common",
    w: 18,
    petal: "#5c6bc0",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleIris: {
    name: "Purple Iris",
    kind: "iris",
    appearance: "iris",
    rarity: "common",
    w: 14,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 6,
  },
  yellowDaffodil: {
    name: "Yellow Daffodil",
    kind: "daffodil",
    appearance: "daffodil",
    rarity: "common",
    w: 18,
    petal: "#fff176",
    stem: "#66bb6a",
    sell: 6,
  },
  whiteDaisy: {
    name: "White Daisy",
    kind: "daisy",
    appearance: "daisy",
    rarity: "common",
    w: 22,
    petal: "#f5f5f5",
    stem: "#66bb6a",
    sell: 5,
  },
  yellowDaisy: {
    name: "Yellow Daisy",
    kind: "daisy",
    appearance: "daisy",
    rarity: "common",
    w: 18,
    petal: "#fff176",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkDaisy: {
    name: "Pink Daisy",
    kind: "daisy",
    appearance: "daisy",
    rarity: "common",
    w: 14,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 6,
  },
  pinkCarnation: {
    name: "Pink Carnation",
    kind: "carnation",
    appearance: "carnation",
    rarity: "common",
    w: 25,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  redCarnation: {
    name: "Red Carnation",
    kind: "carnation",
    appearance: "carnation",
    rarity: "common",
    w: 22,
    petal: "#f44336",
    stem: "#66bb6a",
    sell: 5,
  },
  whiteCarnation: {
    name: "White Carnation",
    kind: "carnation",
    appearance: "carnation",
    rarity: "common",
    w: 20,
    petal: "#fafafa",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleHyacinth: {
    name: "Purple Hyacinth",
    kind: "hyacinth",
    appearance: "hyacinth",
    rarity: "common",
    w: 22,
    petal: "#7b1fa2",
    stem: "#66bb6a",
    sell: 6,
  },
  pinkHyacinth: {
    name: "Pink Hyacinth",
    kind: "hyacinth",
    appearance: "hyacinth",
    rarity: "common",
    w: 18,
    petal: "#ec407a",
    stem: "#66bb6a",
    sell: 6,
  },
  yellowChrysanthemum: {
    name: "Yellow Chrysanthemum",
    kind: "chrysanthemum",
    appearance: "chrysanthemum",
    rarity: "common",
    w: 18,
    petal: "#fdd835",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkChrysanthemum: {
    name: "Pink Chrysanthemum",
    kind: "chrysanthemum",
    appearance: "chrysanthemum",
    rarity: "common",
    w: 16,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  redGeranium: {
    name: "Red Geranium",
    kind: "geranium",
    appearance: "geranium",
    rarity: "common",
    w: 22,
    petal: "#e53935",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkGeranium: {
    name: "Pink Geranium",
    kind: "geranium",
    appearance: "geranium",
    rarity: "common",
    w: 20,
    petal: "#f06292",
    stem: "#66bb6a",
    sell: 5,
  },
  blueBluebell: {
    name: "Blue Bluebell",
    kind: "bluebell",
    appearance: "bluebell",
    rarity: "common",
    w: 20,
    petal: "#7986cb",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleBluebell: {
    name: "Purple Bluebell",
    kind: "bluebell",
    appearance: "bluebell",
    rarity: "common",
    w: 16,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 5,
  },
  yellowMarigold: {
    name: "Yellow Marigold",
    kind: "marigold",
    appearance: "marigold",
    rarity: "common",
    w: 24,
    petal: "#fdd835",
    stem: "#558b2f",
    sell: 5,
  },
  orangeMarigold: {
    name: "Orange Marigold",
    kind: "marigold",
    appearance: "marigold",
    rarity: "common",
    w: 20,
    petal: "#ff8a65",
    stem: "#558b2f",
    sell: 5,
  },
  purplePansy: {
    name: "Purple Pansy",
    kind: "pansy",
    appearance: "pansy",
    rarity: "common",
    w: 22,
    petal: "#7b1fa2",
    stem: "#66bb6a",
    sell: 5,
  },
  yellowPansy: {
    name: "Yellow Pansy",
    kind: "pansy",
    appearance: "pansy",
    rarity: "common",
    w: 20,
    petal: "#fdd835",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkPetunia: {
    name: "Pink Petunia",
    kind: "petunia",
    appearance: "petunia",
    rarity: "common",
    w: 22,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  purplePetunia: {
    name: "Purple Petunia",
    kind: "petunia",
    appearance: "petunia",
    rarity: "common",
    w: 20,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 5,
  },
  yellowPrimrose: {
    name: "Yellow Primrose",
    kind: "primrose",
    appearance: "primrose",
    rarity: "common",
    w: 22,
    petal: "#fff176",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkPrimrose: {
    name: "Pink Primrose",
    kind: "primrose",
    appearance: "primrose",
    rarity: "common",
    w: 18,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleCrocus: {
    name: "Purple Crocus",
    kind: "crocus",
    appearance: "crocus",
    rarity: "common",
    w: 20,
    petal: "#7b1fa2",
    stem: "#66bb6a",
    sell: 5,
  },
  yellowCrocus: {
    name: "Yellow Crocus",
    kind: "crocus",
    appearance: "crocus",
    rarity: "common",
    w: 18,
    petal: "#fdd835",
    stem: "#66bb6a",
    sell: 5,
  },
  orangeCalendula: {
    name: "Orange Calendula",
    kind: "calendula",
    appearance: "calendula",
    rarity: "common",
    w: 22,
    petal: "#ff8a65",
    stem: "#558b2f",
    sell: 5,
  },
  yellowCalendula: {
    name: "Yellow Calendula",
    kind: "calendula",
    appearance: "calendula",
    rarity: "common",
    w: 20,
    petal: "#fdd835",
    stem: "#558b2f",
    sell: 5,
  },
  pinkCosmos: {
    name: "Pink Cosmos",
    kind: "cosmos",
    appearance: "cosmos",
    rarity: "common",
    w: 22,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  whiteCosmos: {
    name: "White Cosmos",
    kind: "cosmos",
    appearance: "cosmos",
    rarity: "common",
    w: 18,
    petal: "#f5f5f5",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkZinnia: {
    name: "Pink Zinnia",
    kind: "zinnia",
    appearance: "zinnia",
    rarity: "common",
    w: 20,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  orangeZinnia: {
    name: "Orange Zinnia",
    kind: "zinnia",
    appearance: "zinnia",
    rarity: "common",
    w: 18,
    petal: "#ff8a65",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkSnapdragon: {
    name: "Pink Snapdragon",
    kind: "snapdragon",
    appearance: "snapdragon",
    rarity: "common",
    w: 18,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  yellowSnapdragon: {
    name: "Yellow Snapdragon",
    kind: "snapdragon",
    appearance: "snapdragon",
    rarity: "common",
    w: 16,
    petal: "#fdd835",
    stem: "#66bb6a",
    sell: 5,
  },
  blueForgetMeNot: {
    name: "Blue Forget-me-not",
    kind: "forgetmenot",
    appearance: "forgetmenot",
    rarity: "common",
    w: 24,
    petal: "#64b5f6",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkAster: {
    name: "Pink Aster",
    kind: "aster",
    appearance: "aster",
    rarity: "common",
    w: 18,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleAster: {
    name: "Purple Aster",
    kind: "aster",
    appearance: "aster",
    rarity: "common",
    w: 16,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 5,
  },
  blueCornflower: {
    name: "Blue Cornflower",
    kind: "cornflower",
    appearance: "cornflower",
    rarity: "common",
    w: 22,
    petal: "#1e88e5",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkImpatiens: {
    name: "Pink Impatiens",
    kind: "impatiens",
    appearance: "impatiens",
    rarity: "common",
    w: 20,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkVerbena: {
    name: "Pink Verbena",
    kind: "verbena",
    appearance: "verbena",
    rarity: "common",
    w: 18,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleHeather: {
    name: "Purple Heather",
    kind: "heather",
    appearance: "heather",
    rarity: "common",
    w: 18,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 6,
  },
  purpleStatice: {
    name: "Purple Statice",
    kind: "statice",
    appearance: "statice",
    rarity: "common",
    w: 20,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 5,
  },
  orangeGerbera: {
    name: "Orange Gerbera Daisy",
    kind: "gerbera",
    appearance: "gerbera",
    rarity: "common",
    w: 20,
    petal: "#ff8a65",
    stem: "#558b2f",
    sell: 5,
  },
  pinkGerbera: {
    name: "Pink Gerbera Daisy",
    kind: "gerbera",
    appearance: "gerbera",
    rarity: "common",
    w: 18,
    petal: "#f48fb1",
    stem: "#558b2f",
    sell: 5,
  },
  blackEyedSusan: {
    name: "Black-eyed Susan",
    kind: "blackeyedsusan",
    appearance: "blackeyedsusan",
    rarity: "common",
    w: 20,
    petal: "#fdd835",
    stem: "#558b2f",
    sell: 5,
  },
  blueSalvia: {
    name: "Blue Salvia",
    kind: "salvia",
    appearance: "salvia",
    rarity: "common",
    w: 18,
    petal: "#3949ab",
    stem: "#33691e",
    sell: 5,
  },
  yellowAlstroemeria: {
    name: "Yellow Alstroemeria",
    kind: "alstroemeria",
    appearance: "alstroemeria",
    rarity: "common",
    w: 18,
    petal: "#fff176",
    stem: "#66bb6a",
    sell: 6,
  },
  orangeNasturtium: {
    name: "Orange Nasturtium",
    kind: "nasturtium",
    appearance: "nasturtium",
    rarity: "common",
    w: 20,
    petal: "#ff8a65",
    stem: "#558b2f",
    sell: 5,
  },
  pinkPhlox: {
    name: "Pink Phlox",
    kind: "phlox",
    appearance: "phlox",
    rarity: "common",
    w: 18,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 5,
  },
  purpleVeronica: {
    name: "Purple Veronica",
    kind: "veronica",
    appearance: "veronica",
    rarity: "common",
    w: 16,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 5,
  },
  pinkSweetPea: {
    name: "Pink Sweet Pea",
    kind: "sweetpea",
    appearance: "sweetpea",
    rarity: "common",
    w: 18,
    petal: "#f8bbd0",
    stem: "#aed581",
    sell: 5,
  },
  yellowWallflower: {
    name: "Yellow Wallflower",
    kind: "wallflower",
    appearance: "wallflower",
    rarity: "common",
    w: 16,
    petal: "#fdd835",
    stem: "#66bb6a",
    sell: 5,
  },
  redGaillardia: {
    name: "Red Gaillardia",
    kind: "gaillardia",
    appearance: "gaillardia",
    rarity: "common",
    w: 16,
    petal: "#f44336",
    stem: "#558b2f",
    sell: 5,
  },
  pinkStock: {
    name: "Pink Stock",
    kind: "stock",
    appearance: "stock",
    rarity: "common",
    w: 18,
    petal: "#f06292",
    stem: "#66bb6a",
    sell: 5,
  },
  // -- Uncommon (46) -------------------------------------------------------
  sunflower: {
    name: "Sunflower",
    kind: "sunflower",
    appearance: "sunflower",
    rarity: "uncommon",
    w: 16,
    petal: "#fdd835",
    stem: "#558b2f",
    sell: 18,
  },
  lavender: {
    name: "Lavender",
    kind: "lavender",
    appearance: "lavender",
    rarity: "uncommon",
    w: 14,
    petal: "#b39ddb",
    stem: "#7cb342",
    sell: 16,
  },
  whiteTulip: {
    name: "White Tulip",
    kind: "tulip",
    appearance: "tulip",
    rarity: "uncommon",
    w: 12,
    petal: "#eceff1",
    stem: "#66bb6a",
    sell: 12,
  },
  redRose: {
    name: "Red Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "uncommon",
    w: 12,
    petal: "#c62828",
    stem: "#43a047",
    sell: 18,
  },
  pinkRose: {
    name: "Pink Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "uncommon",
    w: 8,
    petal: "#e91e63",
    stem: "#43a047",
    sell: 22,
  },
  pinkLily: {
    name: "Pink Lily",
    kind: "lily",
    appearance: "lily",
    rarity: "uncommon",
    w: 12,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 14,
  },
  blueIris: {
    name: "Blue Iris",
    kind: "iris",
    appearance: "iris",
    rarity: "uncommon",
    w: 10,
    petal: "#1976d2",
    stem: "#66bb6a",
    sell: 16,
  },
  whiteDaffodil: {
    name: "White Daffodil",
    kind: "daffodil",
    appearance: "daffodil",
    rarity: "uncommon",
    w: 10,
    petal: "#f5f5f5",
    stem: "#66bb6a",
    sell: 15,
  },
  whiteViolet: {
    name: "White Violet",
    kind: "violet",
    appearance: "violet",
    rarity: "uncommon",
    w: 8,
    petal: "#ede7f6",
    stem: "#66bb6a",
    sell: 14,
  },
  pinkPeony: {
    name: "Pink Peony",
    kind: "peony",
    appearance: "peony",
    rarity: "uncommon",
    w: 10,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 18,
  },
  redPoppy: {
    name: "Red Poppy",
    kind: "poppy",
    appearance: "poppy",
    rarity: "uncommon",
    w: 18,
    petal: "#f44336",
    stem: "#558b2f",
    sell: 15,
  },
  orangePoppy: {
    name: "Orange Poppy",
    kind: "poppy",
    appearance: "poppy",
    rarity: "uncommon",
    w: 14,
    petal: "#ff6d00",
    stem: "#558b2f",
    sell: 16,
  },
  cherryBlossom: {
    name: "Cherry Blossom",
    kind: "cherry",
    appearance: "cherry",
    rarity: "uncommon",
    w: 16,
    petal: "#fce4ec",
    stem: "#795548",
    sell: 20,
  },
  deepCherry: {
    name: "Deep Cherry",
    kind: "cherry",
    appearance: "cherry",
    rarity: "uncommon",
    w: 10,
    petal: "#e91e63",
    stem: "#795548",
    sell: 22,
  },
  yellowRose: {
    name: "Yellow Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "uncommon",
    w: 10,
    petal: "#f9a825",
    stem: "#43a047",
    sell: 20,
  },
  peachRose: {
    name: "Peach Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "uncommon",
    w: 8,
    petal: "#ffcc80",
    stem: "#43a047",
    sell: 20,
  },
  purpleRose: {
    name: "Purple Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "uncommon",
    w: 6,
    petal: "#7b1fa2",
    stem: "#388e3c",
    sell: 25,
  },
  pinkAlstroemeria: {
    name: "Pink Alstroemeria",
    kind: "alstroemeria",
    appearance: "alstroemeria",
    rarity: "uncommon",
    w: 14,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 16,
  },
  blueHyacinth: {
    name: "Blue Hyacinth",
    kind: "hyacinth",
    appearance: "hyacinth",
    rarity: "uncommon",
    w: 12,
    petal: "#1e88e5",
    stem: "#66bb6a",
    sell: 16,
  },
  purpleChrysanthemum: {
    name: "Purple Chrysanthemum",
    kind: "chrysanthemum",
    appearance: "chrysanthemum",
    rarity: "uncommon",
    w: 12,
    petal: "#7b1fa2",
    stem: "#66bb6a",
    sell: 16,
  },
  whiteMagnolia: {
    name: "White Magnolia",
    kind: "magnolia",
    appearance: "magnolia",
    rarity: "uncommon",
    w: 14,
    petal: "#fafafa",
    stem: "#795548",
    sell: 18,
  },
  pinkMagnolia: {
    name: "Pink Magnolia",
    kind: "magnolia",
    appearance: "magnolia",
    rarity: "uncommon",
    w: 10,
    petal: "#ffcdd2",
    stem: "#795548",
    sell: 20,
  },
  redBegonia: {
    name: "Red Begonia",
    kind: "begonia",
    appearance: "begonia",
    rarity: "uncommon",
    w: 14,
    petal: "#f44336",
    stem: "#66bb6a",
    sell: 15,
  },
  pinkBegonia: {
    name: "Pink Begonia",
    kind: "begonia",
    appearance: "begonia",
    rarity: "uncommon",
    w: 12,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 15,
  },
  pinkDahlia: {
    name: "Pink Dahlia",
    kind: "dahlia",
    appearance: "dahlia",
    rarity: "uncommon",
    w: 14,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 18,
  },
  purpleDahlia: {
    name: "Purple Dahlia",
    kind: "dahlia",
    appearance: "dahlia",
    rarity: "uncommon",
    w: 12,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 18,
  },
  orangeDahlia: {
    name: "Orange Dahlia",
    kind: "dahlia",
    appearance: "dahlia",
    rarity: "uncommon",
    w: 10,
    petal: "#ff8a65",
    stem: "#66bb6a",
    sell: 18,
  },
  pinkAzalea: {
    name: "Pink Azalea",
    kind: "azalea",
    appearance: "azalea",
    rarity: "uncommon",
    w: 14,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 16,
  },
  redAnemone: {
    name: "Red Anemone",
    kind: "anemone",
    appearance: "anemone",
    rarity: "uncommon",
    w: 14,
    petal: "#f44336",
    stem: "#66bb6a",
    sell: 15,
  },
  purpleAnemone: {
    name: "Purple Anemone",
    kind: "anemone",
    appearance: "anemone",
    rarity: "uncommon",
    w: 12,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 16,
  },
  yellowFreesia: {
    name: "Yellow Freesia",
    kind: "freesia",
    appearance: "freesia",
    rarity: "uncommon",
    w: 14,
    petal: "#fff176",
    stem: "#66bb6a",
    sell: 16,
  },
  pinkFreesia: {
    name: "Pink Freesia",
    kind: "freesia",
    appearance: "freesia",
    rarity: "uncommon",
    w: 12,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 16,
  },
  pinkGladiolus: {
    name: "Pink Gladiolus",
    kind: "gladiolus",
    appearance: "gladiolus",
    rarity: "uncommon",
    w: 14,
    petal: "#f48fb1",
    stem: "#558b2f",
    sell: 18,
  },
  purpleGladiolus: {
    name: "Purple Gladiolus",
    kind: "gladiolus",
    appearance: "gladiolus",
    rarity: "uncommon",
    w: 12,
    petal: "#9c27b0",
    stem: "#558b2f",
    sell: 18,
  },
  pinkHibiscus: {
    name: "Pink Hibiscus",
    kind: "hibiscus",
    appearance: "hibiscus",
    rarity: "uncommon",
    w: 14,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 18,
  },
  redHibiscus: {
    name: "Red Hibiscus",
    kind: "hibiscus",
    appearance: "hibiscus",
    rarity: "uncommon",
    w: 12,
    petal: "#f44336",
    stem: "#66bb6a",
    sell: 18,
  },
  lilyValley: {
    name: "Lily of the Valley",
    kind: "lilyvalley",
    appearance: "lilyvalley",
    rarity: "uncommon",
    w: 12,
    petal: "#f5f5f5",
    stem: "#aed581",
    sell: 20,
  },
  purpleWisteria: {
    name: "Purple Wisteria",
    kind: "wisteria",
    appearance: "wisteria",
    rarity: "uncommon",
    w: 10,
    petal: "#9c27b0",
    stem: "#795548",
    sell: 22,
  },
  purpleFoxglove: {
    name: "Purple Foxglove",
    kind: "foxglove",
    appearance: "foxglove",
    rarity: "uncommon",
    w: 12,
    petal: "#9c27b0",
    stem: "#558b2f",
    sell: 18,
  },
  pinkFoxglove: {
    name: "Pink Foxglove",
    kind: "foxglove",
    appearance: "foxglove",
    rarity: "uncommon",
    w: 14,
    petal: "#f48fb1",
    stem: "#558b2f",
    sell: 16,
  },
  whiteGardenia: {
    name: "White Gardenia",
    kind: "gardenia",
    appearance: "gardenia",
    rarity: "uncommon",
    w: 10,
    petal: "#fafafa",
    stem: "#43a047",
    sell: 22,
  },
  pinkCyclamen: {
    name: "Pink Cyclamen",
    kind: "cyclamen",
    appearance: "cyclamen",
    rarity: "uncommon",
    w: 12,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 18,
  },
  pinkRanunculus: {
    name: "Pink Ranunculus",
    kind: "ranunculus",
    appearance: "ranunculus",
    rarity: "uncommon",
    w: 12,
    petal: "#f48fb1",
    stem: "#66bb6a",
    sell: 20,
  },
  whiteJasmine: {
    name: "White Jasmine",
    kind: "jasmine",
    appearance: "jasmine",
    rarity: "uncommon",
    w: 12,
    petal: "#fafafa",
    stem: "#aed581",
    sell: 18,
  },
  purpleBuddleia: {
    name: "Purple Buddleia",
    kind: "buddleia",
    appearance: "buddleia",
    rarity: "uncommon",
    w: 12,
    petal: "#9c27b0",
    stem: "#558b2f",
    sell: 18,
  },
  purpleLantana: {
    name: "Purple Lantana",
    kind: "lantana",
    appearance: "lantana",
    rarity: "uncommon",
    w: 12,
    petal: "#9c27b0",
    stem: "#66bb6a",
    sell: 16,
  },
  // -- Rare (27) -----------------------------------------------------------
  tigerLily: {
    name: "Tiger Lily",
    kind: "lily",
    appearance: "lily",
    rarity: "rare",
    w: 4,
    petal: "#ff7043",
    stem: "#558b2f",
    sell: 60,
  },
  goldenIris: {
    name: "Golden Iris",
    kind: "iris",
    appearance: "iris",
    rarity: "rare",
    w: 4,
    petal: "#f9a825",
    stem: "#558b2f",
    sell: 62,
  },
  pinkDaffodil: {
    name: "Pink Daffodil",
    kind: "daffodil",
    appearance: "daffodil",
    rarity: "rare",
    w: 3,
    petal: "#f8bbd0",
    stem: "#558b2f",
    sell: 58,
  },
  redPeony: {
    name: "Red Peony",
    kind: "peony",
    appearance: "peony",
    rarity: "rare",
    w: 3,
    petal: "#e53935",
    stem: "#558b2f",
    sell: 65,
  },
  purpleOrchid: {
    name: "Purple Orchid",
    kind: "orchid",
    appearance: "orchid",
    rarity: "rare",
    w: 3,
    petal: "#ab47bc",
    stem: "#558b2f",
    sell: 68,
  },
  blackTulip: {
    name: "Black Tulip",
    kind: "tulip",
    appearance: "tulip",
    rarity: "rare",
    w: 2,
    petal: "#263238",
    stem: "#1b5e20",
    sell: 70,
  },
  silverRose: {
    name: "Silver Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "rare",
    w: 2,
    petal: "#90a4ae",
    stem: "#546e7a",
    sell: 75,
  },
  crystalDaisy: {
    name: "Crystal Daisy",
    kind: "daisy",
    appearance: "daisy",
    rarity: "rare",
    w: 2,
    petal: "#e3f2fd",
    stem: "#0288d1",
    sell: 65,
  },
  violetPoppy: {
    name: "Violet Poppy",
    kind: "poppy",
    appearance: "poppy",
    rarity: "rare",
    w: 2,
    petal: "#6a1b9a",
    stem: "#1a237e",
    sell: 70,
  },
  goldenCherry: {
    name: "Golden Cherry",
    kind: "cherry",
    appearance: "cherry",
    rarity: "rare",
    w: 1,
    petal: "#f9a825",
    stem: "#5d4037",
    sell: 80,
  },
  midnightRose: {
    name: "Midnight Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "rare",
    w: 1,
    petal: "#37474f",
    stem: "#212121",
    sell: 90,
  },
  purpleCarnation: {
    name: "Purple Carnation",
    kind: "carnation",
    appearance: "carnation",
    rarity: "rare",
    w: 4,
    petal: "#9c27b0",
    stem: "#1b5e20",
    sell: 60,
  },
  pinkFuchsia: {
    name: "Pink Fuchsia",
    kind: "fuchsia",
    appearance: "fuchsia",
    rarity: "rare",
    w: 4,
    petal: "#f06292",
    stem: "#33691e",
    sell: 62,
  },
  purpleClematis: {
    name: "Purple Clematis",
    kind: "clematis",
    appearance: "clematis",
    rarity: "rare",
    w: 4,
    petal: "#7b1fa2",
    stem: "#1b5e20",
    sell: 60,
  },
  blueHydrangea: {
    name: "Blue Hydrangea",
    kind: "hydrangea",
    appearance: "hydrangea",
    rarity: "rare",
    w: 4,
    petal: "#64b5f6",
    stem: "#33691e",
    sell: 62,
  },
  pinkHydrangea: {
    name: "Pink Hydrangea",
    kind: "hydrangea",
    appearance: "hydrangea",
    rarity: "rare",
    w: 3,
    petal: "#f48fb1",
    stem: "#33691e",
    sell: 65,
  },
  whiteCamellia: {
    name: "White Camellia",
    kind: "camellia",
    appearance: "camellia",
    rarity: "rare",
    w: 4,
    petal: "#fafafa",
    stem: "#33691e",
    sell: 60,
  },
  redCamellia: {
    name: "Red Camellia",
    kind: "camellia",
    appearance: "camellia",
    rarity: "rare",
    w: 3,
    petal: "#e53935",
    stem: "#33691e",
    sell: 62,
  },
  pinkLotus: {
    name: "Pink Lotus",
    kind: "lotus",
    appearance: "lotus",
    rarity: "rare",
    w: 3,
    petal: "#f48fb1",
    stem: "#006064",
    sell: 70,
  },
  pinkPlumeria: {
    name: "Pink Plumeria",
    kind: "plumeria",
    appearance: "plumeria",
    rarity: "rare",
    w: 3,
    petal: "#f8bbd0",
    stem: "#5d4037",
    sell: 68,
  },
  pinkBleedingHeart: {
    name: "Pink Bleeding Heart",
    kind: "bleedingheart",
    appearance: "bleedingheart",
    rarity: "rare",
    w: 3,
    petal: "#f48fb1",
    stem: "#558b2f",
    sell: 65,
  },
  blueMorningGlory: {
    name: "Blue Morning Glory",
    kind: "morningglory",
    appearance: "morningglory",
    rarity: "rare",
    w: 3,
    petal: "#1e88e5",
    stem: "#558b2f",
    sell: 65,
  },
  purpleHellebore: {
    name: "Purple Hellebore",
    kind: "hellebore",
    appearance: "hellebore",
    rarity: "rare",
    w: 3,
    petal: "#6a1b9a",
    stem: "#1b5e20",
    sell: 68,
  },
  purpleAllium: {
    name: "Purple Allium",
    kind: "allium",
    appearance: "allium",
    rarity: "rare",
    w: 3,
    petal: "#9c27b0",
    stem: "#558b2f",
    sell: 65,
  },
  purpleGloxinia: {
    name: "Purple Gloxinia",
    kind: "gloxinia",
    appearance: "gloxinia",
    rarity: "rare",
    w: 3,
    petal: "#9c27b0",
    stem: "#33691e",
    sell: 70,
  },
  yellowPlumeria: {
    name: "Yellow Plumeria",
    kind: "plumeria",
    appearance: "plumeria",
    rarity: "rare",
    w: 2,
    petal: "#fff176",
    stem: "#5d4037",
    sell: 72,
  },
  magentaBougainvillea: {
    name: "Magenta Bougainvillea",
    kind: "bougainvillea",
    appearance: "bougainvillea",
    rarity: "rare",
    w: 3,
    petal: "#e91e63",
    stem: "#795548",
    sell: 68,
  },
  // -- Legendary (15) ------------------------------------------------------
  blueRose: {
    name: "Blue Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "legendary",
    w: 3,
    petal: "#3f51b5",
    stem: "#388e3c",
    sell: 60,
  },
  blueTulip: {
    name: "Blue Tulip",
    kind: "tulip",
    appearance: "tulip",
    rarity: "legendary",
    w: 3,
    petal: "#1565c0",
    stem: "#1b5e20",
    sell: 65,
  },
  goldenRose: {
    name: "Golden Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "legendary",
    w: 2,
    petal: "#f9a825",
    stem: "#33691e",
    sell: 75,
  },
  blackRose: {
    name: "Black Rose",
    kind: "rose",
    appearance: "rose",
    rarity: "legendary",
    w: 1,
    petal: "#212121",
    stem: "#1b5e20",
    sell: 85,
  },
  whitePeony: {
    name: "White Peony",
    kind: "peony",
    appearance: "peony",
    rarity: "legendary",
    w: 2,
    petal: "#fafafa",
    stem: "#33691e",
    sell: 80,
  },
  pinkOrchid: {
    name: "Pink Orchid",
    kind: "orchid",
    appearance: "orchid",
    rarity: "legendary",
    w: 2,
    petal: "#f06292",
    stem: "#33691e",
    sell: 85,
  },
  blueOrchid: {
    name: "Blue Orchid",
    kind: "orchid",
    appearance: "orchid",
    rarity: "legendary",
    w: 1,
    petal: "#42a5f5",
    stem: "#1b5e20",
    sell: 90,
  },
  whiteLotus: {
    name: "White Lotus",
    kind: "lotus",
    appearance: "lotus",
    rarity: "legendary",
    w: 3,
    petal: "#fafafa",
    stem: "#006064",
    sell: 80,
  },
  saffron: {
    name: "Saffron Crocus",
    kind: "saffron",
    appearance: "saffron",
    rarity: "legendary",
    w: 2,
    petal: "#ba68c8",
    stem: "#f9a825",
    sell: 85,
  },
  whitePlumeria: {
    name: "White Plumeria",
    kind: "plumeria",
    appearance: "plumeria",
    rarity: "legendary",
    w: 2,
    petal: "#fafafa",
    stem: "#5d4037",
    sell: 80,
  },
  greenHydrangea: {
    name: "Green Hydrangea",
    kind: "hydrangea",
    appearance: "hydrangea",
    rarity: "legendary",
    w: 2,
    petal: "#a5d6a7",
    stem: "#33691e",
    sell: 80,
  },
  whiteWisteria: {
    name: "White Wisteria",
    kind: "wisteria",
    appearance: "wisteria",
    rarity: "legendary",
    w: 2,
    petal: "#fafafa",
    stem: "#795548",
    sell: 82,
  },
  redAmaryllis: {
    name: "Red Amaryllis",
    kind: "amaryllis",
    appearance: "amaryllis",
    rarity: "legendary",
    w: 2,
    petal: "#f44336",
    stem: "#33691e",
    sell: 78,
  },
  orangeBromeliad: {
    name: "Orange Bromeliad",
    kind: "bromeliad",
    appearance: "bromeliad",
    rarity: "legendary",
    w: 2,
    petal: "#ff8a65",
    stem: "#795548",
    sell: 80,
  },
  darkHellebore: {
    name: "Dark Hellebore",
    kind: "hellebore",
    appearance: "hellebore",
    rarity: "legendary",
    w: 1,
    petal: "#4a148c",
    stem: "#1b5e20",
    sell: 90,
  },
  // -- Unique (1) ----------------------------------------------------------
  whiteLily: {
    name: "White Lily",
    kind: "lily",
    appearance: "lily",
    rarity: "unique",
    w: 1,
    petal: "#f5f5f5",
    stem: "#66bb6a",
    sell: 200,
  },
  // -- Hybrid-Only Flowers (cannot drop from packets) ----------------------
  sunsetRose: { name: "Sunset Rose", kind: "rose", appearance: "rose", rarity: "hybrid", w: 0, petal: "#ff7043", stem: "#66bb6a", sell: 45, parents: ["rose", "tulip"] },
  moonlightLily: { name: "Moonlight Lily", kind: "lily", appearance: "lily", rarity: "hybrid", w: 0, petal: "#b0bec5", stem: "#558b2f", sell: 50, parents: ["lily", "violet"] },
  crimsonOrchid: { name: "Crimson Orchid", kind: "orchid", appearance: "orchid", rarity: "hybrid", w: 0, petal: "#c62828", stem: "#33691e", sell: 55, parents: ["orchid", "rose"] },
  goldenDaisy: { name: "Golden Daisy", kind: "daisy", appearance: "daisy", rarity: "hybrid", w: 0, petal: "#ffd600", stem: "#558b2f", sell: 35, parents: ["daisy", "sunflower"] },
  frostedCherry: { name: "Frosted Cherry", kind: "cherry", appearance: "cherry", rarity: "hybrid", w: 0, petal: "#e1bee7", stem: "#66bb6a", sell: 40, parents: ["cherry", "lily"] },
  shadowIris: { name: "Shadow Iris", kind: "iris", appearance: "iris", rarity: "hybrid", w: 0, petal: "#37474f", stem: "#33691e", sell: 50, parents: ["iris", "tulip"] },
  coralPeony: { name: "Coral Peony", kind: "peony", appearance: "peony", rarity: "hybrid", w: 0, petal: "#ff8a65", stem: "#558b2f", sell: 45, parents: ["peony", "poppy"] },
  stardustLavender: { name: "Stardust Lavender", kind: "lavender", appearance: "lavender", rarity: "hybrid", w: 0, petal: "#ce93d8", stem: "#558b2f", sell: 40, parents: ["lavender", "violet"] },
  emeraldTulip: { name: "Emerald Tulip", kind: "tulip", appearance: "tulip", rarity: "hybrid", w: 0, petal: "#4caf50", stem: "#33691e", sell: 55, parents: ["tulip", "iris"] },
  phoenixSunflower: { name: "Phoenix Sunflower", kind: "sunflower", appearance: "sunflower", rarity: "hybrid", w: 0, petal: "#ff5722", stem: "#558b2f", sell: 60, parents: ["sunflower", "rose"] },
  crystalViolet: { name: "Crystal Violet", kind: "violet", appearance: "violet", rarity: "hybrid", w: 0, petal: "#80deea", stem: "#66bb6a", sell: 45, parents: ["violet", "daisy"] },
  midnightPoppy: { name: "Midnight Poppy", kind: "poppy", appearance: "poppy", rarity: "hybrid", w: 0, petal: "#1a237e", stem: "#33691e", sell: 50, parents: ["poppy", "iris"] },
};

export const PKT_POOLS: Record<string, Record<string, number>> = {
  common: {
    // common flowers
    pinkTulip: 30,
    redTulip: 26,
    yellowTulip: 22,
    purpleViolet: 20,
    blueViolet: 18,
    purpleIris: 14,
    yellowDaffodil: 18,
    whiteDaisy: 20,
    yellowDaisy: 16,
    pinkDaisy: 12,
    pinkCarnation: 25,
    redCarnation: 22,
    whiteCarnation: 20,
    purpleHyacinth: 22,
    pinkHyacinth: 18,
    yellowChrysanthemum: 18,
    pinkChrysanthemum: 16,
    redGeranium: 22,
    pinkGeranium: 20,
    blueBluebell: 20,
    purpleBluebell: 16,
    yellowMarigold: 24,
    orangeMarigold: 20,
    purplePansy: 22,
    yellowPansy: 20,
    pinkPetunia: 22,
    purplePetunia: 20,
    yellowPrimrose: 22,
    pinkPrimrose: 18,
    purpleCrocus: 20,
    yellowCrocus: 18,
    orangeCalendula: 22,
    yellowCalendula: 20,
    pinkCosmos: 22,
    whiteCosmos: 18,
    pinkZinnia: 20,
    orangeZinnia: 18,
    pinkSnapdragon: 18,
    yellowSnapdragon: 16,
    blueForgetMeNot: 24,
    pinkAster: 18,
    purpleAster: 16,
    blueCornflower: 22,
    pinkImpatiens: 20,
    pinkVerbena: 18,
    purpleHeather: 18,
    purpleStatice: 20,
    orangeGerbera: 20,
    pinkGerbera: 18,
    blackEyedSusan: 20,
    blueSalvia: 18,
    yellowAlstroemeria: 18,
    orangeNasturtium: 20,
    pinkPhlox: 18,
    purpleVeronica: 16,
    pinkSweetPea: 18,
    yellowWallflower: 16,
    redGaillardia: 16,
    pinkStock: 18,
    // uncommon bleed-through
    sunflower: 5,
    lavender: 4,
    whiteTulip: 4,
    redRose: 6,
    pinkRose: 3,
    redPoppy: 3,
    cherryBlossom: 2,
  },
  uncommon: {
    // uncommon flowers
    sunflower: 22,
    lavender: 18,
    whiteTulip: 14,
    redRose: 18,
    pinkRose: 12,
    pinkLily: 14,
    blueIris: 12,
    whiteDaffodil: 12,
    whiteViolet: 10,
    pinkPeony: 10,
    redPoppy: 18,
    orangePoppy: 14,
    cherryBlossom: 16,
    deepCherry: 10,
    yellowRose: 10,
    peachRose: 8,
    purpleRose: 6,
    pinkAlstroemeria: 14,
    blueHyacinth: 12,
    purpleChrysanthemum: 12,
    whiteMagnolia: 14,
    pinkMagnolia: 10,
    redBegonia: 14,
    pinkBegonia: 12,
    pinkDahlia: 14,
    purpleDahlia: 12,
    orangeDahlia: 10,
    pinkAzalea: 14,
    redAnemone: 14,
    purpleAnemone: 12,
    yellowFreesia: 14,
    pinkFreesia: 12,
    pinkGladiolus: 14,
    purpleGladiolus: 12,
    pinkHibiscus: 14,
    redHibiscus: 12,
    lilyValley: 12,
    purpleWisteria: 10,
    purpleFoxglove: 12,
    pinkFoxglove: 14,
    whiteGardenia: 10,
    pinkCyclamen: 12,
    pinkRanunculus: 12,
    whiteJasmine: 12,
    purpleBuddleia: 12,
    purpleLantana: 12,
    // rare bleed-through
    blueRose: 3,
    blueTulip: 3,
  },
  rare: {
    // rare flowers
    tigerLily: 20,
    goldenIris: 18,
    pinkDaffodil: 16,
    redPeony: 16,
    purpleOrchid: 16,
    blackTulip: 14,
    silverRose: 14,
    crystalDaisy: 14,
    violetPoppy: 14,
    goldenCherry: 12,
    midnightRose: 10,
    purpleCarnation: 12,
    pinkFuchsia: 12,
    purpleClematis: 12,
    blueHydrangea: 12,
    pinkHydrangea: 10,
    whiteCamellia: 12,
    redCamellia: 10,
    pinkLotus: 10,
    pinkPlumeria: 10,
    pinkBleedingHeart: 10,
    blueMorningGlory: 10,
    purpleHellebore: 10,
    purpleAllium: 10,
    purpleGloxinia: 10,
    yellowPlumeria: 8,
    magentaBougainvillea: 10,
    // legendary bleed-through
    blueRose: 8,
    blueTulip: 8,
    goldenRose: 6,
    blackRose: 4,
    whitePeony: 4,
    pinkOrchid: 3,
    blueOrchid: 2,
    whiteLotus: 3,
    saffron: 2,
    whitePlumeria: 2,
    greenHydrangea: 2,
    whiteWisteria: 2,
    redAmaryllis: 2,
    orangeBromeliad: 2,
    darkHellebore: 1,
    whiteLily: 1,
  },
  legendary: {
    // legendary flowers only
    blueRose: 35,
    blueTulip: 35,
    goldenRose: 25,
    blackRose: 15,
    whitePeony: 12,
    pinkOrchid: 10,
    blueOrchid: 8,
    whiteLotus: 10,
    saffron: 8,
    whitePlumeria: 8,
    greenHydrangea: 6,
    whiteWisteria: 6,
    redAmaryllis: 6,
    orangeBromeliad: 5,
    darkHellebore: 4,
    whiteLily: 3,
  },
};
